"""
AI-Assisted Embedded C Documentation Generator
Parses embedded C source files and auto-generates structured Markdown documentation.
Developed with GitHub Copilot assistance.
"""

import re
import sys
from pathlib import Path


def extract_functions(c_code: str) -> list:
    functions = []
    pattern = re.compile(
        r'/\*\*(.*?)\*/\s*\n\s*(\w[\w\s\*]+)\s+(\w+)\s*\(([^)]*)\)',
        re.DOTALL
    )
    for match in pattern.finditer(c_code):
        comment = match.group(1).strip()
        return_type = match.group(2).strip()
        func_name = match.group(3).strip()
        params = match.group(4).strip()
        comment_lines = [
            line.strip().lstrip('*').strip()
            for line in comment.splitlines()
            if line.strip().lstrip('*').strip()
        ]
        functions.append({
            'name': func_name,
            'return_type': return_type,
            'params': params,
            'description': ' '.join(comment_lines)
        })
    return functions


def generate_markdown(filename: str, functions: list) -> str:
    lines = [
        f"# Documentation: `{filename}`\n",
        f"*Auto-generated by ai-embedded-doc-tool*\n",
        "---\n",
        "## Function Index\n",
        "| Function | Return Type | Parameters |",
        "|---|---|---|"
    ]
    for fn in functions:
        lines.append(f"| `{fn['name']}` | `{fn['return_type']}` | `{fn['params']}` |")
    lines.append("\n---\n")
    lines.append("## Detailed Descriptions\n")
    for fn in functions:
        lines.append(f"### `{fn['name']}`")
        lines.append(f"**Returns:** `{fn['return_type']}`  ")
        lines.append(f"**Parameters:** `{fn['params']}`  ")
        lines.append(f"**Description:** {fn['description']}\n")
    return '\n'.join(lines)


def process_file(filepath: str) -> None:
    path = Path(filepath)
    if not path.exists():
        print(f"Error: File not found — {filepath}")
        sys.exit(1)
    with open(path, 'r') as f:
        c_code = f.read()
    functions = extract_functions(c_code)
    if not functions:
        print("No documented functions found.")
        return
    markdown = generate_markdown(path.name, functions)
    output_path = path.with_suffix('.md')
    with open(output_path, 'w') as f:
        f.write(markdown)
    print(f"✅ Documentation generated: {output_path}")
    print(f"   Found {len(functions)} documented function(s).")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python doc_generator.py <path_to_c_file>")
        sys.exit(1)
    process_file(sys.argv[1])
